# Generated by Django 3.0.5 on 2020-07-12 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(default=datetime.datetime(2020, 7, 12, 16, 21, 14, 827941), verbose_name='Due Date')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('complete', models.BooleanField(default=False, verbose_name='Completed')),
            ],
        ),
    ]
