# Generated by Django 3.0.5 on 2020-07-12 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 18, 24, 6, 843320), verbose_name='Due Date'),
        ),
    ]
