# Generated by Django 3.0.5 on 2020-07-12 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20200712_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 18, 38, 5, 575401), verbose_name='Due Date'),
        ),
    ]
